
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://flora.db.elephantsql.com/vsuxeqni
    username: vsuxeqni
    password: Mm-3oHYT8YwaAvZobMvp0J1AVEPVT46V
    hikari:
      maximum-pool-size: 100   # Adjust this value as neede
      connection-timeout: 30000  # Adjust this value as needed (in milliseconds)


  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 8088

  
